/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
//    id ("com.github.ryuzu.java-conventions")
    id("java-library")
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://jitpack.io")
    }
    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }
    maven {
        url = uri("https://repo.codemc.io/repository/maven-public/")
    }
}

group = "com.github.ryuzu"
version = "1.0.0"

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

dependencies {
    api(project(":searchableinfiniteshop-plugin"))
    api(project(":searchableinfiniteshop-v16newer"))
    api(project(":searchableinfiniteshop-v16older"))
    api(project(":searchableinfiniteshop-api"))
}

java.sourceCompatibility = JavaVersion.VERSION_11
description = "Searchable Infinite Shop Plugin"
