/*
 * This file was generated by the Gradle "init" task.
 */

plugins {
//    id ("com.github.ryuzu.java-conventions")
    id("java-library")
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://jitpack.io")
    }
    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }
    maven {
        url = uri("https://repo.codemc.io/repository/maven-public/")
    }
}

group = "com.github.ryuzu"
version = "1.0.0"

//publishing {
//    publications {
//        maven(MavenPublication) {
//            from(components.java)
//        }
//    }
//}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

dependencies {
//    api "com.github.Y-RyuZU:RyuZUCommandsGenerator:2.0.3"
//    api "de.tr7zw:item-nbt-api-plugin:2.11.2"
    api(project(":searchableinfiniteshop-plugin"))
    api(project(":searchableinfiniteshop-v16newer"))
    api(project(":searchableinfiniteshop-v16older"))
    api(project(":searchableinfiniteshop-api"))
//    compileOnly "org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT"
//    compileOnly "org.projectlombok:lombok:1.18.26"
//    compileOnly "com.mojang:authlib:1.5.21"
//    compileOnly("net.citizensnpcs:citizens-main:2.0.30-SNAPSHOT") {
//        exclude group: "*", module: "*"
//    }
}

java.sourceCompatibility = JavaVersion.VERSION_1_8
description = "Searchable Infinite Shop Plugin"

//tasks {
//    processResources {
//        filteringCharset = "UTF-8"
//        duplicatesStrategy = DuplicatesStrategy.INCLUDE
//        filesMatching("plugin.yml") {
//            expand(mapOf("version" to project.version))
//        }
//    }
//}
